In [1]:
! pip install scikit-learn

   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.1 MB 6.6 MB/s eta 0:00:02
   ----------- ---------------------------- 2.4/8.1 MB 7.9 MB/s eta 0:00:01
   ------------------ --------------------- 3.7/8.1 MB 8.4 MB/s eta 0:00:01
   -------------------- ------------------- 4.2/8.1 MB 5.6 MB/s eta 0:00:01
   ---------------------- ----------------- 4.5/8.1 MB 5.1 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.1 MB 4.5 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.1 MB 4.3 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.1 MB 4.2 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 4.2 MB/s  0:00:01

   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
  


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
! pip install --upgrade pip

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------------- ---------------------- 0.8/1.8 MB 1.6 MB/s eta 0:00:01
   ----------------------- ---------------- 1.0/1.8 MB 1.6 MB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 1.9 MB/s  0:00:01
  Attempting uninstall: pip
    Found existing installation: pip 25.2
    Uninstalling pip-25.2:
      Successfully uninstalled pip-25.2


In [3]:
from sklearn import datasets

In [6]:
data=datasets.load_breast_cancer()


In [8]:
print(data)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], shape=(569, 30)), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,

In [13]:
import pandas as pd
df=pd.read_csv("E:\Data analytics\__pycache__\CAR DETAILS FROM CAR DEKHO.csv")
print(df)
df.head()

                                     name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individ

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner


In [15]:
x= df.drop("selling_price",axis=1)
y=df["selling_price"]
x

,name,year,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,90000,Diesel,Individual,Manual,First Owner


In [17]:
from sklearn.model_selection import train_test_split    
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)


In [21]:
x_train


,name,year,km_driven,fuel,seller_type,transmission,owner
227,Mahindra Scorpio S11 BSIV,2017,20000,Diesel,Individual,Manual,First Owner
964,Maruti Swift Dzire VDI,2018,50000,Diesel,Individual,Manual,First Owner
2045,Maruti Alto 800 LXI,2013,25000,Petrol,Individual,Manual,Second Owner
1025,Chevrolet Beat Diesel LS,2011,70000,Diesel,Individual,Manual,First Owner
4242,Maruti Vitara Brezza LDi Option,2017,72000,Diesel,Dealer,Manual,First Owner
...,...,...,...,...,...,...,...
3444,Toyota Innova 2.5 G (Diesel) 8 Seater BS IV,2006,50000,Diesel,Individual,Manual,First Owner
466,Tata Indica Vista Quadrajet LX,2011,80000,Diesel,Individual,Manual,First Owner
3092,Maruti Ciaz VDi Plus SHVS,2016,51000,Diesel,Dealer,Manual,First Owner
3772,Maruti Ertiga VDI,2013,80000,Diesel,Individual,Manual,First Owner


In [22]:
x_train.shape

(3472, 7)

In [23]:
x_test

,name,year,km_driven,fuel,seller_type,transmission,owner
3978,Tata Manza Aqua Quadrajet BS IV,2010,80000,Diesel,Individual,Manual,First Owner
1448,Renault KWID RXT BSIV,2019,27000,Petrol,Individual,Manual,First Owner
2664,Hyundai Santro Xing GL Plus,2008,41723,Petrol,Individual,Manual,Second Owner
17,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner
1634,Mahindra TUV 300 T8 AMT,2016,60000,Diesel,Individual,Automatic,Second Owner
...,...,...,...,...,...,...,...
3468,Maruti Wagon R LXI Minor,2007,60000,Petrol,Individual,Manual,Third Owner
3164,Maruti Celerio ZDi,2015,120000,Diesel,Individual,Manual,First Owner
416,Maruti Ritz VDi,2011,40000,Diesel,Individual,Manual,Second Owner
1616,Toyota Etios Liva 1.2 VX,2017,6480,Petrol,Trustmark Dealer,Manual,First Owner


In [25]:
x_test.shape

(868, 7)

Applying Normalization : Minmax Scalling

In [50]:
import pandas as pd
df=pd.read_csv("E:\Data analytics\__pycache__\CAR DETAILS FROM CAR DEKHO.csv")
print(df)

                                     name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individ

In [51]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner


In [52]:
df=df[["selling_price","km_driven","year"]]
print(df)

      selling_price  km_driven  year
0             60000      70000  2007
1            135000      50000  2007
2            600000     100000  2012
3            250000      46000  2017
4            450000     141000  2014
...             ...        ...   ...
4335         409999      80000  2014
4336         409999      80000  2014
4337         110000      83000  2009
4338         865000      90000  2016
4339         225000      40000  2016

[4340 rows x 3 columns]


In [53]:
df

,selling_price,km_driven,year
0,60000,70000,2007
1,135000,50000,2007
2,600000,100000,2012
3,250000,46000,2017
4,450000,141000,2014
...,...,...,...
4335,409999,80000,2014
4336,409999,80000,2014
4337,110000,83000,2009
4338,865000,90000,2016


In [54]:
from sklearn.preprocessing  import MinMaxScaler
scaler=MinMaxScaler()
df_new=scaler.fit_transform(df)
df_new

array([[0.0045045 , 0.08678301, 0.53571429],
       [0.01295045, 0.06198751, 0.53571429],
       [0.06531532, 0.12397626, 0.71428571],
       ...,
       [0.01013514, 0.10290008, 0.60714286],
       [0.09515766, 0.11157851, 0.85714286],
       [0.02308559, 0.04958976, 0.85714286]], shape=(4340, 3))

In [55]:
df_new


array([[0.0045045 , 0.08678301, 0.53571429],
       [0.01295045, 0.06198751, 0.53571429],
       [0.06531532, 0.12397626, 0.71428571],
       ...,
       [0.01013514, 0.10290008, 0.60714286],
       [0.09515766, 0.11157851, 0.85714286],
       [0.02308559, 0.04958976, 0.85714286]], shape=(4340, 3))

In [56]:
df

,selling_price,km_driven,year
0,60000,70000,2007
1,135000,50000,2007
2,600000,100000,2012
3,250000,46000,2017
4,450000,141000,2014
...,...,...,...
4335,409999,80000,2014
4336,409999,80000,2014
4337,110000,83000,2009
4338,865000,90000,2016


In [57]:
s_df = pd.DataFrame(df_new, columns=df.columns)


Standardscaler

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [23]:
df= pd.read_csv("E:\Data analytics\__pycache__\Social_Network_Ads.csv")
print(df)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [24]:
df.drop("User ID",axis=1,inplace=True)
df

,Gender,Age,EstimatedSalary,Purchased
0,Male,19,19000,0
1,Male,35,20000,0
2,Female,26,43000,0
3,Female,27,57000,0
4,Male,19,76000,0
...,...,...,...,...
395,Female,46,41000,1
396,Male,51,23000,1
397,Female,50,20000,1
398,Male,36,33000,0


In [25]:
df["Gender"] =df["Gender"].map({"Male":1, "Female":0})
df

,Gender,Age,EstimatedSalary,Purchased
0,1,19,19000,0
1,1,35,20000,0
2,0,26,43000,0
3,0,27,57000,0
4,1,19,76000,0
...,...,...,...,...
395,0,46,41000,1
396,1,51,23000,1
397,0,50,20000,1
398,1,36,33000,0


traain test split

In [27]:
from sklearn.model_selection import train_test_split
x=df.drop("Purchased",axis=1)
y=df["Purchased"]

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [29]:
x_train

,Gender,Age,EstimatedSalary
3,0,27,57000
18,1,46,28000
202,0,39,134000
250,0,44,39000
274,0,57,26000
...,...,...,...
71,0,24,27000
106,0,26,35000
270,0,43,133000
348,1,39,77000


StandardScaler


In [30]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [31]:
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-1.        , -1.06675246, -0.38634438],
       [ 1.        ,  0.79753468, -1.22993871],
       [-1.        ,  0.11069205,  1.853544  ],
       [-1.        ,  0.60129393, -0.90995465],
       [-1.        ,  1.87685881, -1.28811763],
       [ 1.        , -0.57615058,  1.44629156],
       [ 1.        ,  0.3069328 , -0.53179168],
       [ 1.        ,  0.99377543,  0.10817643],
       [ 1.        , -1.16487283,  0.45724994],
       [ 1.        , -1.55735433,  0.31180264],
       [ 1.        ,  1.0918958 ,  0.45724994],
       [-1.        , -0.18366908, -0.47361276],
       [ 1.        ,  0.20881242, -0.32816546],
       [-1.        ,  0.3069328 ,  0.28271318],
       [ 1.        , -1.16487283, -1.57901222],
       [-1.        ,  0.11069205,  0.25362372],
       [ 1.        ,  2.07309956,  1.73718616],
       [ 1.        ,  0.40505317, -0.18271817],
       [-1.        ,  1.4843773 ,  2.11534913],
       [ 1.        , -0.37990983,  1.21357589],
       [-1.        ,  1.87685881,  1.504

In [32]:
x_test

array([[-1.        ,  0.79753468, -1.40447546],
       [-1.        ,  2.07309956,  0.51542886],
       [-1.        , -0.96863208, -0.76450736],
       [-1.        ,  0.99377543,  0.74814454],
       [-1.        , -0.87051171, -1.22993871],
       [-1.        , -0.77239133, -0.24089709],
       [-1.        ,  0.89565505,  1.06812859],
       [-1.        , -0.87051171,  0.36998156],
       [ 1.        ,  0.20881242,  0.13726589],
       [ 1.        ,  0.40505317, -0.15362871],
       [-1.        , -0.28178945, -0.15362871],
       [-1.        ,  1.4843773 , -1.05540195],
       [-1.        , -1.45923396, -0.64814952],
       [-1.        , -1.75359508, -1.37538601],
       [ 1.        , -0.77239133,  0.4863394 ],
       [ 1.        , -0.28178945,  1.09721805],
       [-1.        ,  1.38625693, -0.93904411],
       [-1.        ,  0.79753468,  0.10817643],
       [ 1.        ,  0.11069205, -0.82268628],
       [ 1.        ,  1.77873843, -0.29907601],
       [-1.        , -1.55735433, -1.259

In [33]:
x_train

array([[-1.        , -1.06675246, -0.38634438],
       [ 1.        ,  0.79753468, -1.22993871],
       [-1.        ,  0.11069205,  1.853544  ],
       [-1.        ,  0.60129393, -0.90995465],
       [-1.        ,  1.87685881, -1.28811763],
       [ 1.        , -0.57615058,  1.44629156],
       [ 1.        ,  0.3069328 , -0.53179168],
       [ 1.        ,  0.99377543,  0.10817643],
       [ 1.        , -1.16487283,  0.45724994],
       [ 1.        , -1.55735433,  0.31180264],
       [ 1.        ,  1.0918958 ,  0.45724994],
       [-1.        , -0.18366908, -0.47361276],
       [ 1.        ,  0.20881242, -0.32816546],
       [-1.        ,  0.3069328 ,  0.28271318],
       [ 1.        , -1.16487283, -1.57901222],
       [-1.        ,  0.11069205,  0.25362372],
       [ 1.        ,  2.07309956,  1.73718616],
       [ 1.        ,  0.40505317, -0.18271817],
       [-1.        ,  1.4843773 ,  2.11534913],
       [ 1.        , -0.37990983,  1.21357589],
       [-1.        ,  1.87685881,  1.504

In [34]:
x_train_scaled=pd.DataFrame(data=x_train,columns=x_train.columns)
x_test_scaled=pd.DataFrame(data=x_test,columns=x_test.columns)

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

AttributeError: 'numpy.ndarray' object has no attribute 'describe'